title: Joshua Paul
logo: Headshot.jpg
description: <A href="https://www.linkedin.com/in/joshua-paul-77a932193"/>Linkedin</A> <br /> <A href="https://drive.google.com/file/d/1UZSdbXCqgL7f3nDO_ErBtYBWDxBZAb-z/view?usp=drive_link">Link to Detailed Portfolio</A> <br /> <A href="https://drive.google.com/file/d/1Z2oD_q0_1FQGoYYVXENNT4vOl6H6Zv7k/view?usp=sharing">Link to Resume</A> 
theme: jekyll-theme-minimal
