title: Joshua Paul
logo: Headshot.jpg
description: <A href="https://www.linkedin.com/in/joshua-paul-77a932193"/>Linkedin</A> <br /> <a href="Joshua Paul Embedded Software Portfolio.pdf" > Embedded Software Porfolio </a> <br /> <a href="Joshua Paul Software Portfolio.pdf" > Software Porfolio </a> <br /> <A href="https://drive.google.com/file/d/1Z2oD_q0_1FQGoYYVXENNT4vOl6H6Zv7k/view?usp=sharing">Link to Resume</A> 
theme: jekyll-theme-minimal
