title: Joshua Paul
logo: Headshot.jpg
description: 
<A href="https://docs.google.com/presentation/d/1gFziXP8IPxsRFcvgIu8lnYPRqxgm4jdaDLlgYsf6-eE/edit?usp=sharing">Link to Detailed Portfolio</A>
theme: jekyll-theme-minimal
